#### Preamble ####
# Purpose: Generates a simulated version of the Toronto Shelter System dataset
# Author: Jianing Li
# Date: September 23, 2024
# Contact: lijianing.li@mail.utoronto.ca
# License: MIT
# Pre-requisites: Install the tidyverse (Wickham et al. 2019) package.
# Any other information needed? None

#### Workspace setup ####
library(tidyverse)


#### Simulate data ####
# Set random seed to ensure reproducibility
set.seed(500)

# Simulate a date column from January 2018 to August 2024, monthly
# Generated by ChatGPT
dates <- seq(as.Date("2018-01-01"), as.Date("2024-08-01"), by = "month")

# Simulate population groups
population_groups <- c("Chronic", "All populations")

# Generate random homeless counts
homeless_count <- sample(1000:3000, length(dates) * length(population_groups), replace = TRUE)

# Generate random age group counts
age_under_16 <- sample(100:500, length(dates) * length(population_groups), replace = TRUE)
age_16_24 <- sample(100:500, length(dates) * length(population_groups), replace = TRUE)
age_25_34 <- sample(100:500, length(dates) * length(population_groups), replace = TRUE)
age_35_44 <- sample(100:500, length(dates) * length(population_groups), replace = TRUE)
age_45_54 <- sample(100:500, length(dates) * length(population_groups), replace = TRUE)
age_55_64 <- sample(100:500, length(dates) * length(population_groups), replace = TRUE)
age_65_over <- sample(100:500, length(dates) * length(population_groups), replace = TRUE)

# Generate random gender counts
male_count <- sample(500:1500, length(dates) * length(population_groups), replace = TRUE)
female_count <- sample(500:1500, length(dates) * length(population_groups), replace = TRUE)
transgender_non_binary_count <- sample(10:100, length(dates) * length(population_groups), replace = TRUE)

# Create a simulated data frame with all variables
simulated_data <- data.frame(
  Date = rep(dates, each = length(population_groups)),
  Population_Group = rep(population_groups, times = length(dates)),
  Homeless_Count = homeless_count,
  Age_Under_16 = age_under_16,
  Age_16_24 = age_16_24,
  Age_25_34 = age_25_34,
  Age_35_44 = age_35_44,
  Age_45_54 = age_45_54,
  Age_55_64 = age_55_64,
  Age_65_Over = age_65_over,
  Male_Count = male_count,
  Female_Count = female_count,
  Transgender_Non_Binary_Count = transgender_non_binary_count
)

# Save the simulated data to the specified path
write.csv(simulated_data, "/Users/liz/Downloads/starter_folder-main/data/raw_data/simulated_shelter_data.csv", row.names = FALSE)

