#### Preamble ####
# Purpose: Tests the validity of the simulated dataset.
# Author: Jianing Li
# Date: September 23, 2024
# Contact: lijianing.li@mail.utoronto.ca
# License: MIT
# Pre-requisites: Simulated dataset from "00-simulate_data.R".
# Any other information needed? None

#### Workspace setup ####
library(tidyverse)

#### Test data ####
# Load the dataset
simulated_data <- read.csv("/Users/liz/Downloads/starter_folder-main/data/raw_data/simulated_shelter_data.csv")

# Check the structure of the dataset
# Generated by ChatGPT
str(simulated_data)

# Check the first few rows of the data to ensure it loaded correctly
head(simulated_data)

# Test for missing values
any_na <- any(is.na(simulated_data))
if (any_na) {
  print("There are missing values in the dataset.")
} else {
  print("No missing values in the dataset.")
}

# Check the range of homeless counts
range_homeless <- range(simulated_data$Homeless_Count)
if (range_homeless[1] >= 1000 & range_homeless[2] <= 3000) {
  print("Homeless_Count is within the expected range (1000 to 3000).")
} else {
  print("Homeless_Count is outside the expected range.")
}

# Check the range of age groups
range_age_16_24 <- range(simulated_data$Age_16_24)
if (range_age_16_24[1] >= 100 & range_age_16_24[2] <= 500) {
  print("Age_16_24 is within the expected range (100 to 500).")
} else {
  print("Age_16_24 is outside the expected range.")
}

# Check the range of Male_Count
range_male <- range(simulated_data$Male_Count)
if (range_male[1] >= 500 & range_male[2] <= 1500) {
  print("Male_Count is within the expected range (500 to 1500).")
} else {
  print("Male_Count is outside the expected range.")
}

# Check the range of Female_Count
range_female <- range(simulated_data$Female_Count)
if (range_female[1] >= 500 & range_female[2] <= 1500) {
  print("Female_Count is within the expected range (500 to 1500).")
} else {
  print("Female_Count is outside the expected range.")
}

# Check the range of Transgender/Non-Binary counts
range_trans_nb <- range(simulated_data$Transgender_Non_Binary_Count)
if (range_trans_nb[1] >= 10 & range_trans_nb[2] <= 100) {
  print("Transgender_Non_Binary_Count is within the expected range (10 to 100).")
} else {
  print("Transgender_Non_Binary_Count is outside the expected range.")
}

# Check the range of dates
date_range <- range(as.Date(simulated_data$Date))
expected_start_date <- as.Date("2018-01-01")
expected_end_date <- as.Date("2024-08-01")

if (date_range[1] == expected_start_date & date_range[2] == expected_end_date) {
  print("Dates are within the expected range (January 2018 to August 2024).")
} else {
  print("Dates are outside the expected range.")
}

# Check if dates are in ascending order
if (all(diff(as.Date(simulated_data$Date)) >= 0)) {
  print("Dates are in the correct order.")
} else {
  print("Dates are not in the correct order.")
}

# Check for duplicate rows
duplicates <- simulated_data[duplicated(simulated_data), ]
if (nrow(duplicates) == 0) {
  print("No duplicate rows in the dataset.")
} else {
  print("There are duplicate rows in the dataset.")
}


